#!/bin/sh

# to run this script:
#   - make sure you have the class p4_java.class
#   - run with "./test.sh TEST_CASE_NUM"
#   - e.g. "./test.sh 00"
OUTDIR=output

echo "Test with test$1.tog:"
echo "Use your compiler to translate .tog to .s"
java p4_java <../tests/input/test$1.tog >$OUTDIR/test$1.s

echo "--------------------------------------------"
echo "Use gcc to assemble .s your compiler generated:"
gcc -g -o $OUTDIR/test$1 $OUTDIR/test$1.s

echo "--------------------------------------------"
echo "Run executable generated by gcc:"
$OUTDIR/test$1

echo "--------------------------------------------"
echo "Assemble and run provided .s sample:"
gcc -g -o $OUTDIR/test$1_sample  ../tests/output/test$1.s
$OUTDIR/test$1_sample


